export const AJAX_CALL_ERROR   = 'AJAX_CALL_ERROR';
export const AJAX_CALL_SUCCESS = 'AJAX_CALL_SUCCESS';
export const BEGIN_AJAX_CALL   = 'BEGIN_AJAX_CALL';
export const LOAD_PORTFOLIO_SUCCESS        = 'LOAD_PORTFOLIO_SUCCESS';
export const ON_PORTFOLIO_FILTER           = 'ON_PORTFOLIO_FILTER';
export const ON_RESTORE_PORTFOLIO          = 'ON_RESTORE_PORTFOLIO';
export const ON_TICKER_BEGIN_DATE_SORT     = 'ON_TICKER_BEGIN_DATE_SORT';
export const ON_TICKER_CYCLE_SORT          = 'ON_TICKER_CYCLE_SORT';
export const ON_TICKER_HIGHEST_DATE_SORT   = 'ON_TICKER_HIGHEST_DATE_SORT';
export const ON_TICKER_HIGHEST_NETPER_SORT = 'ON_TICKER_HIGHEST_NETPER_SORT';
export const ON_TICKER_LOWEST_DATE_SORT    = 'ON_TICKER_LOWEST_DATE_SORT';
export const ON_TICKER_LOWEST_NETPER_SORT  = 'ON_TICKER_LOWEST_NETPER_SORT';

