export const AAPL   = 'AAPL';   // Apple Computer
export const AMZN   = 'AMZN';   // Amazon
export const BABA   = 'BABA';   // Alibaba
export const BTC    = 'BTC';    // Bitcoin
export const CRM    = 'CRM';    // Salesforce
export const DAX    = 'GDAXI';  // $DAX (Germany)
export const FB     = 'FB';     // Facebook
export const GLD    = 'GLD';    // Gold ETF
export const GOOGL  = 'GOOGL';  // Google
export const IYR    = 'IYR';    // Housing ETF
export const KOSPI  = 'KS11';   // $KS11 (Korea)
export const MSFT   = 'MSFT';   // Microsoft
export const NASDAQ = 'NASDAQ'; // $COMPQ (Nasdaq)
export const NFLX   = 'NFLX';   // Netflex
export const NVDA   = 'NVDA';   // NVidia
export const SHCOMP = 'SHCOMP'; // Shanghai (China)
export const SLV    = 'SLV';    // Silver ETF
export const SPX    = 'SPX';    // $SPX
export const TAIEX  = 'TAIEX';  // Taiwan Wighted
export const TQQQ   = 'TQQQ';   // QQQ 3X Bull
export const TRAN   = 'TRAN';   // $TRAN
export const TSLA   = 'TSLA';   // Tesla
export const TSM    = 'TSM';    // Taiwan Semi
export const XLE    = 'XLE';    // Energy ETF
export const XLF    = 'XLF';    // Financial ETF
