import React from 'react';

class AboutPage extends React.Component {
  render() {
    return(
      <div>
        <h2>About</h2>
        <hr/>
        <ul>
          <li>The application uses <span className="colorOrange">React</span>,&nbsp;
            <span className="colorOrange">Redux</span>,&nbsp;
            <span className="colorOrange">React-Router</span>, and&nbsp;
            <span className="colorOrange">other libraries</span> to provide the market changes view.
            The context of the view is provided by the weekly computed JSON data generated by the Java program that
            implements the principles embedded in <i>The Book of Change</i>, aka <i>I-Ching</i>.
          </li><br/>
          <li>You may search a ticker from the portfolio by the provided filter input box but you can not add
            any new tickers that are not in the list. This is the current constraint due to budget. The system
            computes the market data once a week--i.e., the daily close market data is entered manually over the
            weekend for the Java program to compute.
          </li><br/>
          <li>
            The situation code has a five-digit format, ABCDE, in which CD refers to the original sequence
            number listed in <i>The Book of Change</i>, E is the CD's internal state verse numbered from 1 (beginning)
            to 6 (top), and AB is the system's internal sequence number that stands for 1 as Qian 乾,
            2 as Dui 兑, 3 Li 離, 4 Zhen 震, 5 Xun 巽, 6 Kan 坎, 7 Gen 艮, 8 Kun 坤.&nbsp;
            <span className="colorBlue">The context of ABCDE metaphorically depicts the ensuing development of the
            addressed market in the Cycle.</span>
          </li><br/>
          <li>
            For the situation text displayed to the user, only the text of the CD is listed. Readers have to
            refer to the <i>Book</i> for the E as the CD's internal state description.
          </li><br/>
          <li>
            The Cycle-I-yang is triggered by a price rise, Cycle-II-yin by a price drop.&nbsp;
            The Cycle sometimes lasts 2-3 years.&nbsp;
            <span className="colorBlue">It is the yin/yang phenomenon that Cycle-I always pans out a top and Cycle-II a bottom.</span>&nbsp;
            Readers may use the provided stock chart to identify the top/bottom.
          </li>
        </ul>
        <hr/>
        <p>
          Current Portfolio:
        </p>
        <hr/>
        <p>
          <i>Disclaimer:</i>
        </p>
      </div>
    );
  }
}

export default AboutPage;
